### ISSUE TITLE
Problem with table indexing and pseudo classes

### ISSUE THREAD

**Issue by Truhera** [css4j/css4j#12] opened 2022-03-01 11:01 UTC
Hello,

I am trying to generate XHTML with applying CSS to it. I am struggling with following CSS Code:

`table#corporate tr:first-child {
 background-color:#002a55;
 color:#fff;
 font-weight:bold
}
table#corporate tr:nth-child(odd):not(:first-child) {
 background-color:#f5f5f5;
 color:#000;
}
table#corporate tr:nth-child(even) {
 background-color:#fff;
 color:#000
}`

This should be applied to a table:

`<table id="corporate">
							<tbody>
								<tr>
									<td>Test</td>
									<td>.</td>
								</tr>
								<tr>
									<td>.</td>
									<td>.</td>
								</tr>
								<tr>
									<td>.</td>
									<td>.</td>
								</tr>
								<tr>
									<td>.</td>
									<td>.</td>
								</tr>
								<tr>
									<td>.</td>
									<td>.</td>
								</tr>
							</tbody>
						</table>`

but the CSS only get's applied to the first 4 table rows, the last row is skipped every time I use some kind of pseudoclass selectors.
I also tried specifically selecting the 5th nth-child but with no luck. I think the algorithm stops at the last entry of the table row entries.

The HTML after applying CSS:

`<table id="corporate">  
 							<tbody>  
 								<tr style="background-color: #002a55; color: #fff; font-weight: bold; ">  
 									<td>Test</td>
 									<td>.</td>
 								</tr>
 								<tr style="background-color: #fff; color: #000; ">
 									<td>.</td>
 									<td>.</td>
 								</tr>
								<tr style="background-color: #f5f5f5; color: #000; ">
									<td>.</td>
									<td>.</td>
								</tr>
								<tr style="background-color: #fff; color: #000; ">
									<td>.</td>
									<td>.</td>
								</tr>
								<tr>
									<td>.</td>
									<td>.</td>
								</tr>
							</tbody>
						</table>`

The css4j version I'm using: css4j 3.7.1

**Comment by carlosame** [comment] 2022-03-01 14:54
I managed to reproduce the problem with css4j-dom4j. Working on a patch.

**Comment by carlosame** [comment] 2022-03-01 16:25
The issue is fixed in `master`, fix will be released in css4j 3.7.2 and css4j-dom4j 3.7.1.

Unless you have more issues to report, I'll release the new versions soon.

**Closed by carlosame** 2022-03-01 16:25 UTC
Labels: bug

**Comment by carlosame** [comment] 2022-03-02 20:24
Now both css4j 3.7.2 and css4j-dom4j 3.7.1 are released with the fix. Thank you @Truhera for reporting this bug.
